set-option -sa terminal-overrides ",xterm*:Tc"

set -g prefix C-a
unbind C-b
bind-key C-a send-prefix

# Navigasi ke Kiri (Previous Window)
bind -n C-j previous-window
bind -n C-k next-window

bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

unbind '"'
unbind %

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

set -g @plugin 'tmux-plugins/tpm'             # Wajib ada
set -g @plugin 'tmux-plugins/tmux-sensible'   # Settingan dasar biar gak glitch
set -g @plugin 'Nybkox/tmux-kanagawa'         # Theme pilihanmu
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

# 2. Konfigurasi Resurrect (Opsional tapi sangat membantu)
set -g @resurrect-capture-pane-contents 'on' # Menyimpan isi text di dalam pane
set -g @resurrect-strategy-nvim 'session'    # Untuk restore sesi Neovim

# 3. Konfigurasi Continuum
set -g @continuum-restore 'off'               # Otomatis restore saat tmux dijalankan
set -g @continuum-save-interval '10'         # Interval auto-save (dalam menit)
set -g @kanagawa-plugins "network ssh-session"
set -g @kanagawa-show-empty-plugins false
set -g @kanagawa-show-network-ethernet true
set -g status-position top 
# set -g pane-border-status top
# set -g pane-border-format ""
set -g @kanagawa-theme 'wave'                 # Pilihan: wave, lotus, dragon
set -g @kanagawa-ignore-window-colors true    # Biar background nyatu sama terminal (Transparent support)

set -g @kanagawa-left-separator "█"
set -g @kanagawa-right-separator "█"

set -g @kanagawa-show-flags true
set -g @kanagawa-refresh-rate 5

run '~/.tmux/plugins/tpm/tpm'
